### ISSUE TITLE
نسخه اندرویدی

### ISSUE THREAD

**Issue by xc0000e9** [Kazem-ma79/CFScanner#1]
روی اندورید ۱۳ تست هر دفعه به یک عدد میرسه و متوقف میشه. در صورت رفتن به برنامه دیگه یا قسمت های دیگه خود برنامه مثل دامین چک تمام اطلاعت اسکنر پاک میشه و عملیات متوقف میشه و تا بستن برنامه و باز کردن مجدد امکان شروع تست جدید نیست.

**Comment by Kazem-ma79** [comment]
بله فیلد های برنامه با جا به جایی بین صفحات ریست میشن
در واقع موقع جابجایی بین صفحات، صفحه قبلی از حافظه رم حذف شده و صفحه جدید باز میشه
مورد آخر رو واضح تر توضیح بدین لطفاً. توی حالت های مختلف با جابجایی بین صفحات تست کردیم ولی مشکلی روی عملکرد برنامه ایجاد نشد.
