### ISSUE TITLE
ابهامات

### ISSUE THREAD

**Issue by The-Binary-0-1** [Kazem-ma79/CFScanner#2]
سلام. اول خسته نباشید... ضمنا...
توضیح ندادید ساب دامین یا دامینی که وارد میکنیم پشت کلادفلر باشه یا نباشه؟
پورت v2ray نوشتید منظورتون پورتی هست که روی سرور کانفیگ ساختیم؟ پورت ساکس v2ray روی ویندوز که در حال اجرا هست؟ پورت چی دقیقا؟
آی پی و دامنه ای که مطمئن هستم داره کار میکنم رو وارد میکنم ولی باز پیغام فیلتر بودن میده در حالت چک کردن. چرا ؟
در حالت اسکن هم که در چندین حالت مختلف چک کردم چند هزار آی پی اسکن کرد و هیچی پیدا نشد!

**Comment by Kazem-ma79** [comment]
سلام
دامنه ای که وارد میکنید پشت کلادفلر باشه.
پورت v2ray منظور پورتی هست که به کانفیگتون اختصاص دادین.
فیلدهای ورودی رو به درستی پر کنید عملیات اسکن بدون مشکل اجرا میشه.

**Comment by HamedABC66** [comment]
سلام. اون آی پی هایی که پیدا میکنه رو چطور استفاده کنم؟ به چه کار میاد. متوجه نشدم
