### ISSUE TITLE
Export IPs

### ISSUE THREAD

**Issue by aliafshany** [Kazem-ma79/CFScanner#3]
سلام
آیا ممکن هست که قابلیتی اضافه کنید تا تمامی آیپی هایی که پیدا شدند رو بشه اکسپورت کرد؟

همچنین وقتی که تب جدیدی میریم و میایم تمامی نتایج از بین میرن. اون رو هم اگر بشه رفع کنید.

آیا میشه یک لیست آیپی با فرمت txt به قسمت domain checker داد تا بر اساس اون ایپی های اوکی رو در نهایت اکسپورت گرفت؟

**Comment by Kazem-ma79** [comment]
سلام

مورد دوم رو حل کردیم توی ورژن جدید که به زودی منتشر میشه.
مورد اول و سوم هم در آپدیت های بعدی اضافه میکنیم.
